Name = "Soup.CSharp.Compiler.Roslyn"
Language = "C#|0.1"
Version = "0.4.1"
Source = [
	"ArgumentBuilder.cs",
	"Compiler.cs",
]

[Dependencies]
Runtime = [
	"Opal@1.0.1",
	"Soup.CSharp.Compiler@0.4.1",
	"Soup.Build.Extensions@0.2.0",
	"Soup.Build.Extensions.Utilities@0.2.1",
]