Name = "Soup.CSharp.Compiler.Roslyn"
Language = "C#"
Version = "0.1.6"
Source = [
	"ArgumentBuilder.cs",
	"Compiler.cs",
]

[Dependencies]
Runtime = [
	"Opal@1.0.1",
	"Soup.CSharp.Compiler@0.1.5",
	"Soup.Build.Extensions@0.1.8",
]