Version = 1
[Projects]
"C#" = [
	{ Name = "Soup.CSharp", Version = "./" },
	{ Name = "Opal", Version = "1.0.3" },
	{ Name = "Soup.Build", Version = "0.1.3" },
	{ Name = "Soup.Build.Extensions", Version = "0.2.0" },
	{ Name = "Soup.CSharp.Compiler", Version = "0.4.0" },
	{ Name = "Soup.Build.Extensions.Utilities", Version = "0.2.0" },
	{ Name = "Soup.CSharp.Compiler.Roslyn", Version = "0.4.0" },
]
