Name = "Soup.CSharp"
Language = "C#"
Version = "0.4.0"

Source = [
	"Tasks/BuildTask.cs",
	"Tasks/RecipeBuildTask.cs",
	"Tasks/ResolveDependenciesTask.cs",
	"Tasks/ResolveToolsTask.cs",
]

[Dependencies]
Runtime = [
	{ Reference = "Opal@1.0.3" },
	{ Reference = "Soup.Build@0.1.3", ExcludeRuntime = true },
	{ Reference = "Soup.Build.Extensions@0.2.0" },
	{ Reference = "Soup.Build.Extensions.Utilities@0.1.0" },
	{ Reference = "Soup.CSharp.Compiler@0.4.0" },
	{ Reference = "Soup.CSharp.Compiler.Roslyn@0.4.0" },
]